baseURL = 'http://bordalos.com/'

languageCode = 'en-us'
DefaultContentLanguage = "en"
Title = 'Bordalos on the Web 3.0'
theme = "color-your-world"


[menu]
[[menu.main]]
  identifier = 'about'
  name = 'about'
  pre = "<i class='fa fa-heart'></i>"
  url = '/about'
  weight = -110
[[menu.main]]
  identifier = 'blog'
  name = 'posts'
  pre = "<i class='fa fa-heart'></i>"
  url = '/posts/'
  weight = -110


Paginate = 5

[Author]
  name ="Bordalos"
  bio = "Hi folks."
  avatar = ""


[params]
  favicon = ""
  site_logo = ""
  subtitle = "Just another site" # Subtitle of your site
  description = "This is my website" # Description of your site
  twitter = ""
  youtube = ""
  github = ""
  gitlab = ""
  rss = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/web-image.jpg"
  recent_posts_number = 2

  # Footer text
  # Each value will become a paragraph
  # Keep it as an array
  footerText = [ "Generated with [Hugo](https://gohugo.io) using the [Color Your World](https://gitlab.com/rmaguiar/hugo-theme-color-your-world) theme." ]
    
  # Site cover, for Open Graph, Twitter Cards and Schema.org
  # It will be used if the current page doesn't have an image cover
  # File will be picked from the "assets" directory
  # Comment the lines if you don't want to use it
  cover     = "img/cover.jpg"
  coverAlt  = "A placeholder that doesn't deserve to be described."

  # Shows a message in the footer about JavaScript being disabled
  # The default is false
  hasNoscriptNotice = true

  # Default path for images in posts
  # ie.: "content/some-post/img"
  # Can also be set PER PAGE
  # It can be used to reduce repetition
  # There's no default value
  imgPath = "img"

  # Default classes for markup image
  # Modifies the default behavior of images placed via markdown
  # Can also be set PER PAGE via front matter
  # Available classes are: border and borderless
  # There's no default value
  markupImgClass = "borderless"

  # This will append a separator (of your choice) along the site title to your <title>
  # ie.: | ❚ - – — • ⚫
  # You can disabled it PER PAGE by using "disableTitleSeparator" at front
  # matter or disable it entirely by commenting the line below
  titleSeparator = "|"



  [params.style]

    # Dark mode as default
    # User preferences (site/system settings) will still have priority over it
    # The default is false
    isDark = false

    # Accent colors for dark and light mode respectively
    darkAccent   = "#1dbc91" # Default is "#1dbc91"
    lightAccent  = "#1f676b" # Default is "#1f676b"

    # More colors, pick as many as you want (not really sure if there's a limit)
    # Apparently these may not show up on every modern browser (ie.: Firefox)
    # There's no default value. Used here just as example
    presets = [ "#1f676b", "#f3a530", "#902b37", "#1dbc91", "#754e85", "#7fc121", "#a8314a", "#ff7433", "#3e6728", "#c063bd" ]

  [params.notFound]
    title         = "Page not found"
    description   = "This page was not found."
    paragraph     = "Nothing to see here, buddy."
