title = 'Bordalos on Web3'
baseURL = 'http://bordalos.com/'
languageCode = 'en-us'
theme = "ananke"

[params]
  author = "Bordalos"
  favicon = ""
  site_logo = ""
  description = ""
  facebook = ""
  twitter = ""
  instagram = ""
  youtube = ""
  github = ""
  gitlab = ""
  linkedin = ""
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/web-image.jpg"
  recent_posts_number = 2